name: Sync and Commit PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full
      shell: bash

    - name: Configure Git Credentials
      run: |
        git_creds="${{ secrets.GH_GIT_CREDENTIALS }}"
        git config --global credential.helper store <<< "${git_creds}"
        git config --global user.name "azizosharke"
        git config --global user.email "abdelaza@tcd.ie"
      shell: bash

    - name: Build and Commit PDF
      run: |
        # Compile LaTeX to generate PDF
        pdflatex -interaction=nonstopmode main.tex

        # Add, commit, and push the PDF
        git add main.pdf
        git commit -m "Update PDF"
        git push
      shell: bash
