name: Compile LaTeX document

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LaTeX and dependencies
      run: sudo apt-get install texlive-full texlive-bibtex-extra biber
    - name: Compile LaTeX document using Makefile
      run: make all
    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add $(ROOTNAME).pdf
        git commit -m "Update $(ROOTNAME).pdf" -a || echo "No changes to commit"
        git push --set-upstream https://${{ secrets.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 }}@github.com/USERNAME/REPOSITORY.git main
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: $(ROOTNAME).pdf
