name: Compile LaTeX document

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if it's named differently

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LaTeX and dependencies
      run: sudo apt-get install texlive-full texlive-bibtex-extra biber
    - name: Compile LaTeX document using Makefile
      run: make all
    - name: Commit PDF
      env:
        ROOTNAME: main  # Define the variable here for use in this step
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add $ROOTNAME.pdf
        git commit -m "Update $ROOTNAME.pdf" -a || echo "No changes to commit"
        git push --set-upstream https://${{ secrets.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 }}@github.com/azizosharke/FinalYearCapstoneProject.git main
    - name: Upload PDF as artifact
      env:
        ROOTNAME: main  # Define the variable here for use in this step
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: ${{ env.ROOTNAME }}.pdf
