name: Compile LaTeX document

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install LaTeX
      run: sudo apt-get install texlive-full

    - name: Compile LaTeX document
      run: pdflatex main.tex

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add main.pdf
        git commit -m "Update main.pdf" -a || echo "No changes to commit"
        git push --set-upstream https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/azizosharke/FinalYearCapstoneProject.git main

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: main.pdf
