name: Sync and Commit PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Commit PDF
      run: |
        # Compile LaTeX to generate PDF
        pdflatex -interaction=nonstopmode main.tex

        # Configure Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Add, commit, and push the PDF
        git add main.pdf
        git commit -m "Update PDF"
        git push
