name: Compile LaTeX document

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if it's named differently

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LaTeX and dependencies
      run: sudo apt-get install texlive-full texlive-bibtex-extra biber
    - name: Compile LaTeX document using Makefile
      run: make all
    - name: Commit and push PDF if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add main.pdf
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update main.pdf" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
