name: Compile LaTeX document

on:
  push:
    branches:
      - main  # Replace with your default branch if it's not 'main'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      ROOTNAME: main  # Define your ROOTNAME variable here

    steps:
    - uses: actions/checkout@v2

    - name: Install LaTeX
      run: sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Compile LaTeX Document
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error $ROOTNAME.tex
        bibtex $ROOTNAME
        pdflatex -interaction=nonstopmode -halt-on-error $ROOTNAME.tex
        pdflatex -interaction=nonstopmode -halt-on-error $ROOTNAME.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-PDF
        path: ${{ env.ROOTNAME }}.pdf

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{ env.ROOTNAME }}.pdf
        git commit -m "Update PDF" -a || echo "No changes to commit"
        git push
