jobs:
  build:
    steps:
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run unit tests
      run: python -m unittest discover -s tests/unit
    - name: Run UI tests
      run: python -m unittest discover -s tests/ui
